### Create a new patient Entity
POST http://localhost:4000/patients
Content-Type: application/json

{
    "name": "Toriqul Islam",
    "email": "tts@mil.com",
    "address": "Dhaka",
    "dateOfBirth": "2000-01-21",
    "registeredDate": "2025-10-01"
}

###