### Update an existing patient entity
PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174014
Content-Type: application/json

{
  "name": "Toriqul Islam",
  "email": "tts@gmail.com",
  "address": "Dhaka",
  "dateOfBirth": "2000-01-21"
}

###